import {
  buildAlertItems,
  calculateHealthScore,
  formatParameterLabel,
  getLatestReport,
} from "../utils/patientIntelligence";

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function exportAiHealthSummary({ profile, reports, trends, insights, selectedReport = null }) {
  const activeReport = selectedReport || getLatestReport(reports);
  const healthScore = calculateHealthScore(reports, trends, insights);
  const alerts = buildAlertItems(reports, trends, insights);
  const anomalies = trends?.anomalies || [];
  const trendSummary = trends?.summary || [];
  const patient = activeReport?.report_metadata?.patient || {};
  const lab = activeReport?.report_metadata?.lab || {};
  const reportInfo = activeReport?.report_metadata?.report || {};
  const parameters = activeReport?.parameters || [];

  const html = `
    <html>
      <head>
        <title>AI Health Summary</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 32px; color: #0f172a; }
          h1, h2, h3 { margin-bottom: 8px; }
          .muted { color: #64748b; }
          .card { border: 1px solid #cbd5e1; border-radius: 16px; padding: 16px; margin: 16px 0; }
          .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
          ul { padding-left: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          th, td { border-bottom: 1px solid #e2e8f0; padding: 10px; text-align: left; vertical-align: top; }
        </style>
      </head>
      <body>
        <h1>AI Health Summary</h1>
        <p class="muted">Generated by DoctorCopilot</p>

        <div class="card">
          <h2>Patient Info</h2>
          <div class="grid">
            <div><strong>Name:</strong> ${escapeHtml(profile?.user?.full_name || patient.full_name || "Unknown")}</div>
            <div><strong>Age:</strong> ${escapeHtml(profile?.age || patient.age || "Unknown")}</div>
            <div><strong>Gender:</strong> ${escapeHtml(profile?.gender || patient.gender || "Unknown")}</div>
            <div><strong>Blood Group:</strong> ${escapeHtml(profile?.blood_group || "Unknown")}</div>
          </div>
        </div>

        <div class="card">
          <h2>Health Score</h2>
          <p><strong>${escapeHtml(healthScore.score)}</strong> - ${escapeHtml(healthScore.status)}</p>
          <p>${escapeHtml(healthScore.explanation)}</p>
        </div>

        <div class="card">
          <h2>Report Summary</h2>
          <div class="grid">
            <div><strong>Report Date:</strong> ${escapeHtml(reportInfo.report_date || activeReport?.report_date || "Unknown")}</div>
            <div><strong>Lab:</strong> ${escapeHtml(lab.lab_name || activeReport?.lab_name || "Unknown")}</div>
            <div><strong>Type:</strong> ${escapeHtml(activeReport?.report_type || reportInfo.report_type || "Medical Report")}</div>
            <div><strong>Category:</strong> ${escapeHtml(activeReport?.report_category || "other")}</div>
          </div>
        </div>

        <div class="card">
          <h2>Parameter Table</h2>
          <table>
            <thead>
              <tr><th>Parameter</th><th>Value</th><th>Range</th><th>Status</th></tr>
            </thead>
            <tbody>
              ${
                parameters.length
                  ? parameters
                      .map(
                        (parameter) => `
                          <tr>
                            <td>${escapeHtml(formatParameterLabel(parameter.name))}</td>
                            <td>${escapeHtml(parameter.value)} ${escapeHtml(parameter.unit || "")}</td>
                            <td>${escapeHtml(parameter.reference_range || "-")}</td>
                            <td>${escapeHtml(parameter.status || parameter.interpretation || "unknown")}</td>
                          </tr>
                        `
                      )
                      .join("")
                  : `<tr><td colspan="4">No structured parameters available.</td></tr>`
              }
            </tbody>
          </table>
        </div>

        <div class="card">
          <h2>AI Insights</h2>
          <ul>${alerts.map((item) => `<li>${escapeHtml(item.title)}</li>`).join("") || "<li>No abnormal findings highlighted.</li>"}</ul>
        </div>

        <div class="card">
          <h2>Trend Summary</h2>
          <ul>${trendSummary.map((item) => `<li>${escapeHtml(item)}</li>`).join("") || "<li>No comparative trend insights available yet.</li>"}</ul>
        </div>

        <div class="card">
          <h2>Anomaly Section</h2>
          <ul>${anomalies.map((item) => `<li>${escapeHtml(item.message)}</li>`).join("") || "<li>No significant anomalies currently detected.</li>"}</ul>
        </div>
      </body>
    </html>
  `;

  const printWindow = window.open("", "_blank", "noopener,noreferrer,width=960,height=720");
  if (!printWindow) {
    throw new Error("Unable to open export window.");
  }

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 350);
}

export const ExportService = {
  exportAiHealthSummary,
};

export default ExportService;
